### ISSUE TITLE
Notas de Débito aparecen como in_refund

### ISSUE THREAD

**Issue by nelsonramirezs** [dansanti/l10n_cl_invoice#16]
El comportamiento contable actualmente es igual al de la nota de crédito pero debe ser igual que una factura. 
sign = self.invoice_id.type in ['in_refund', 'out_refund'] and -1 or 1

**Comment by dansanti** [comment]
Hola! se supone había reparado eso, ya que cuando se crea una ND, se cambia el tipo de out_refund a out_invoice, y in_refund a in_invoice, voy revisar el código, puede que haya vuelto a estar asignando para toda nota  como tipo refund
