### ISSUE TITLE
Plantillas para el plan contable

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_invoice#4]
En el archivo https://github.com/dansanti/l10n_cl_invoice/blob/9.0/data/tax.xml, se hace referencia a campos que no existen en el modelo account.tax.template, por lo que al instalar el modulo, los impuestos no se cargan correctamente, podriamos separar esos registros a un modulo independiente que sea solamente para el plan contable????

**Comment by dansanti** [comment]
por ahora los estoy dejando como referencia, me he olvidado en crear los campos en model correspondiente, sin embargoel modulo de balances que estoy haciendo llevará los planes contables según la SVS.

A modo de avance , agregaré  los campos al model tax.template

**Comment by celm1990** [comment]
cierro esto en V11 esta ya
