### ISSUE TITLE
Error en migracion de codigo a nueva api

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_invoice#6]
En el commit [Agrego Nota de crédito y
Actualizo código a la api de 9.0](https://github.com/dansanti/l10n_cl_invoice/commit/e3edf40c057cb6b33048863015a4b96cf1a39318) se paso el codigo a la nueva api, pero en la definicion del campo debit_notes se dejo una coma de mas que sale un error al actualizar el modulo.

_ERROR ? openerp.models: Trailing comma after field definition: <class 'openerp.addons.l10n_cl_invoice.wizard.journal_config_wizard.account_journal_document_config'>.debit_notes_

[coma de mas](https://github.com/dansanti/l10n_cl_invoice/blob/9.0/wizard/journal_config_wizard.py#L18)

**Comment by dansanti** [comment]
Hay que tener ojo de que ese wizard hay que reestructurarlo, ya que en multiempresa genera resultados no esperados
